### ISSUE TITLE
Broken link in “Advanced APIs Overview”

### ISSUE THREAD

**Issue by merc1er** [Ankr-network/ankr-docs#736]
It seems like the roadmap link [here](https://github.com/Ankr-network/ankr-docs/blame/1c0d23df05987c8aa4004ca23079daecc3876754/pages/build/products/advanced-api-sdk/overview.md#L91) links to a non-existent page.

Link: https://roadmap.ankr.com/b/feature-requests/

**Comment by raproid** [comment]
Thanks! We're fixing the issue.

**Comment by galleon8** [comment]
Hi @merc1er. Thanks for your interest in adding new features to our Roadmap. Currently, we do some maintenance at the initial URL provided, and it's been unavailable since.

But we definitely DO like to hear from you — please join our Discord community (http://discord.gg/ankr) to propose new features, get support from our team, or have a chat with like-minded developers.

We have also fixed the docs accordingly (https://www.ankr.com/docs/advanced-api/overview/#support-and-developer-community).

Thanks again, and kind regards from our team.
